Quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', include('questions.urls'))
]

questions/urls.py
from django.urls import path
from . import views


app_name = 'questions'

urlpatterns = [
    path('', views.home_page, name = "home_page"),
    path('quiz/', views.quiz, name = "quiz1"),
    path('next/', views.next_question, name = "next")
]

questions/models.py
from django.db import models

# Create your models here.

questions/views.py
from django.shortcuts import render
import requests
import json
import random
from questions import utils

    #if ["questions", "type", "score"] not in request.session:
    #    request.session["questions"] = []
    #    request.session["type"] = []
    #    request.session["score"] = []
    #else:
    #    pass
# Create your views here.




def home_page(request):

    request.session["q_index"] = 0
    request.session["category"] = ""
    print(request.session["q_index"])

    request.session["token"] = utils.get_session_token()

    return render(request, 'questions/home5.html')



def quiz(request):

    if request.method == "GET":      
        request.session["score"] = 0
        request.session["chosen_category_id"] = "0"

        
        request.session["category_name_list"] = []

        categories = utils.get_categories_dict()
        for num in categories["trivia_categories"]:
            request.session["category_name_list"].append(num["name"])
            


        return render(request, "questions/quiz_home.html", {
            "list": request.session["category_name_list"]
        })


    else:

        request.session["category"] = request.POST["category"]
        request.session["difficulty"] = request.POST["difficulty"]


        categories = utils.get_categories_dict()
        chosen_category_id = []

        for num in categories["trivia_categories"]:
            if num["name"] == request.session["category"]:
                chosen_category_id.append(num["id"])
            else:
                continue

        request.session["chosen_category_id"] = chosen_category_id[0]
        print("category id is:" + f'{request.session["chosen_category_id"]}')


        question_answers_dct = utils.get_question_answers_dct(request.session["token"], str(request.session["chosen_category_id"]), request.session["difficulty"])
        request.session["question_answers_dct"] = question_answers_dct

        print(request.session["question_answers_dct"])



        if len(list(request.session["question_answers_dct"].values())[request.session["q_index"]]) == 2:

            return render(request, "questions/test2.html", {
                "question": list(request.session["question_answers_dct"].keys())[request.session["q_index"]]  
            })

        else:

            while True:

                opt = []

                option1 = list(request.session["question_answers_dct"].values())[request.session["q_index"]][random.randint(0, 3)]
                opt.append(option1)

                option2 = list(request.session["question_answers_dct"].values())[request.session["q_index"]][random.randint(0, 3)]
                opt.append(option2)

                option3 = list(request.session["question_answers_dct"].values())[request.session["q_index"]][random.randint(0, 3)]
                opt.append(option3)

                option4 = list(request.session["question_answers_dct"].values())[request.session["q_index"]][random.randint(0, 3)]
                opt.append(option4)

                if len(opt) == len(set(opt)):
                    break
                else:
                    continue


            return render(request, "questions/test.html", {
                "question": list(request.session["question_answers_dct"].keys())[request.session["q_index"]],
                "option1": opt[0],
                "option2": opt[1],
                "option3": opt[2],
                "option4": opt[3],              
            })





def next_question(request):
    try:
        if request.method == "POST":     
            correct = list(request.session["question_answers_dct"].values())[request.session["q_index"]][0]

            if "bool" in list(request.POST.keys()):
                if request.POST["bool"] == correct:
                    request.session["score"] += 1
                else:
                    pass 
            
            else:
                if request.POST["opt"] == correct:
                    request.session["score"] += 1
                else:
                    pass

            print(request.session["score"])


            request.session["q_index"] += 1

            if len(list(request.session["question_answers_dct"].values())[request.session["q_index"]]) == 2:

                return render(request, "questions/test2.html", {
                    "question": list(request.session["question_answers_dct"].keys())[request.session["q_index"]]  
                })

            else:

                while True:

                    opt = []

                    option1 = list(request.session["question_answers_dct"].values())[request.session["q_index"]][random.randint(0, 3)]
                    opt.append(option1)

                    option2 = list(request.session["question_answers_dct"].values())[request.session["q_index"]][random.randint(0, 3)]
                    opt.append(option2)

                    option3 = list(request.session["question_answers_dct"].values())[request.session["q_index"]][random.randint(0, 3)]
                    opt.append(option3)

                    option4 = list(request.session["question_answers_dct"].values())[request.session["q_index"]][random.randint(0, 3)]
                    opt.append(option4)

                    if len(opt) == len(set(opt)):
                        break
                    else:
                        continue

                print(opt)


                return render(request, "questions/test.html", {
                    "question": list(request.session["question_answers_dct"].keys())[request.session["q_index"]],                
                    "option1": opt[0],
                    "option2": opt[1],
                    "option3": opt[2],
                    "option4": opt[3],         
                })

    except:

        return render(request, "questions/score.html", {
            "score": request.session["score"]
        })







    

questions/templates/questions/home5.html
{% extends "questions/layout.html" %}

{% block title %}
    Quiz
{% endblock %}

{% block body %}

    <a href = "{% url 'questions:quiz1' %}">
        <input type = "button" value = "Go To Quiz App">
    </a>

{% endblock %}

questions/templates/questions/index.html
{% extends "questions/layout.html" %}

{% block title %}
    index
{% endblock %}

{% block body %}

    <h1>Quiz</h1>

    <form action = "{% url 'questions:quiz1' %}" method = "POST">

        {% csrf_token %}

        <label for = "category">Choose Category:</label>
        <select id = "category" name = "category">
            {% for item in list %}
                <option value="{{ item }}">{{ item }}</option>
            {% empty %}
                <p>No Categories</p>
            {% endfor %}
        </select>
        
        <br>
        <br>

        <label for = "difficulty">Choose Difficulty:</label>
        <select id = "difficulty" name = "difficulty">
            <option value = "easy">Easy</option>
            <option value = "medium">Medium</option>
            <option value = "hard">Hard</option>
        </select>    

        <br>
        <br>

        <input type = "submit" value = "Start Quiz">

      </form>





{% endblock %}

questions/templates/questions/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel = "stylesheet">
    </head>
    <body>

        {% block body %}
        
        {% endblock %}

    </body>
</html>

questions/templates/questions/quiz.html
{% extends "questions/layout.html" %}

{% block title %}
    Quiz
{% endblock %}

{% block body %}

    <h1>Quiz</h1>

    <p>Question: {{ question }}</p>


{% endblock %}

questions/templates/questions/quiz_bool.html
{% extends "questions/layout.html" %}

{% block title %}
    Quiz
{% endblock %}

{% block body %}

    <h1>Quiz</h1>

    <br>
    <br>

    <h3>Question Nubmer {{ index }}</h3>
    <br>
    <br>

    <form action = "{% url 'questions:quiz1' %}" method = "post">

        {% csrf_token %}

        <p>{{ question }}</p>
        <input type="radio" id="1" name="bool" value="True">
        <label for="1">True</label><br>
        <input type="radio" id="2" name="bool" value="False">
        <label for="2">False</label><br>

        <br>
        <br>

        <input type = "submit" value = "Answer">

        <br>
        <br>

    </form>

    <form action = "{% url 'questions:quiz1' %}" method = "GET">
        <input type = "submit" value = "Skip Question">
    </form>



    <br>
    <br>

    <a href = "{% url 'questions:index' %}">
        <input type = "button" value = "cancel quiz">
    </a>

    






{% endblock %}

questions/templates/questions/quiz_home.html
{% extends "questions/layout.html" %}

{% block title %}
    index
{% endblock %}

{% block body %}

    <h1>Quiz</h1>

    <form action = "{% url 'questions:quiz1' %}" method = "POST">

        {% csrf_token %}

        <label for = "category">Choose Category:</label>
        <select id = "category" name = "category">
            {% for item in list %}
                <option value="{{ item }}">{{ item }}</option>
            {% empty %}
                <p>No Categories</p>
            {% endfor %}
        </select>
        
        <br>
        <br>

        <label for = "difficulty">Choose Difficulty:</label>
        <select id = "difficulty" name = "difficulty">
            <option value = "easy">Easy</option>
            <option value = "medium">Medium</option>
            <option value = "hard">Hard</option>
        </select>    

        <br>
        <br>

        <input type = "submit" value = "Start Quiz">

      </form>

      <br>
      <br>



{% endblock %}

questions/templates/questions/quiz_multiple.html
{% extends "questions/layout.html" %}

{% block title %}
    Quiz
{% endblock %}

{% block body %}

    <h1>Quiz</h1>

    <br>
    <br>

    <h3>Question Nubmer {{ index }}</h3>

    <br>
    <br>

    <form action = "{% url 'questions:quiz1' %}" method = "post">

        {% csrf_token %}

        <p>{{ question }}</p>
        <input type="radio" id="1" name="opt" value="{{ option1 }}">
        <label for="1">{{ option1 }}</label><br>
        <input type="radio" id="2" name="opt" value="{{ option2 }}">
        <label for="2">{{ option2 }}</label><br>
        <input type="radio" id="3" name="opt" value="{{ option3 }}">
        <label for="3">{{ option3 }}</label><br>
        <input type="radio" id="4" name="opt" value="{{ option4 }}">
        <label for="4">{{ option4 }}</label><br>


        <br>
        <br>

        <input type = "submit" value = "Answer">

        <br>
        <br>

    </form>

    <form action = "{% url 'questions:quiz1' %}" method = "GET">
        <input type = "submit" value = "Skip Question">
    </form>



    <br>
    <br>

    <a href = "{% url 'questions:index' %}">
        <input type = "button" value = "cancel quiz">
    </a>

    






{% endblock %}

questions/templates/questions/score.html
{% extends "questions/layout.html" %}

{% block title %}
    index
{% endblock %}

{% block body %}

    <h1>Score: {{ score }} out of 10</h1>

    <a href = "{% url 'questions:home_page' %}">
        <input type = "button" value = "Go Back To Main Page">
    </a>


{% endblock %}

questions/templates/questions/test.html
{% extends "questions/layout.html" %}

{% block title %}
    Quiz
{% endblock %}

{% block body %}

    <h1>Question:</h1>

    <br>
    <br>

    <form action = "{% url 'questions:next' %}" method = "POST">
        {% csrf_token %}

        <p>{{ question }}</p>
        <input type="radio" id="1" name="opt" value="{{ option1 }}">
        <label for="1">{{ option1 }}</label><br>
        <input type="radio" id="2" name="opt" value="{{ option2 }}">
        <label for="2">{{ option2 }}</label><br>
        <input type="radio" id="3" name="opt" value="{{ option3 }}">
        <label for="3">{{ option3 }}</label><br>
        <input type="radio" id="4" name="opt" value="{{ option4 }}">
        <label for="4">{{ option4 }}</label><br>


        <br>
        <br>

        <input type = "submit" value = "Answer">

        <br>
        <br>
        
    </form>

    <a href = "{% url 'questions:home_page' %}">
        <input type = "button" value = "Go Back To Home Page">
    </a>

{% endblock %}

questions/templates/questions/test2.html
{% extends "questions/layout.html" %}

{% block title %}
    Quiz
{% endblock %}

{% block body %}

    <h1>Question:</h1>


    <form action = "{% url 'questions:next' %}" method = "POST">
        {% csrf_token %}

        <p>{{ question }}</p>
        <input type="radio" id="1" name="bool" value="True">
        <label for="1">True</label><br>
        <input type="radio" id="2" name="bool" value="False">
        <label for="2">False</label><br>

        <br>
        <br>

        <input type = "submit" value = "Answer">

        <br>
        <br>

    </form>

    <a href = "{% url 'questions:home_page' %}">
        <input type = "button" value = "Go Back To Home Page">
    </a>

{% endblock %}